import assert from 'node:assert/strict';
import { chromium } from 'playwright';
const base = process.env.BASE_URL || 'http://127.0.0.1:4173';
const browser = await chromium.launch();
try {
  for (const width of [390, 1366]) {
    const context = await browser.newContext({viewport:{width,height:900},serviceWorkers:'block'});
    const page = await context.newPage();
    await page.route('**/testimony-config.js*', route => route.fulfill({contentType:'application/javascript',body:"window.TESTIMONY_CONFIG={supabaseUrl:'https://test.supabase.co',supabaseAnonKey:'public-key',turnstileSiteKey:'test',submissionsEnabled:true};"}));
    await page.route('**/challenges.cloudflare.com/**', route => route.fulfill({contentType:'application/javascript',body:"window.turnstile={render(host,opts){window.cap=opts;opts.callback('valid');return 'id'},reset(){window.cap.callback('valid')}};"}));
    await page.goto(base+'/');
    const draft = page.locator('#home-letter-draft');
    assert.equal(await draft.getAttribute('required'),'');
    await page.locator('#home-letter-form button').click();
    assert.equal(new URL(page.url()).pathname,'/');
    const words = 'Dear Saint Charbel, I want to tell my own story of prayer and hope. '.repeat(10);
    const startHeight = await draft.evaluate(el => el.clientHeight);
    await draft.fill(words);
    const grown = await draft.evaluate(el => ({height:el.clientHeight,scrollHeight:el.scrollHeight}));
    assert.ok(grown.height > startHeight && grown.height + 5 >= grown.scrollHeight, `textarea should grow at ${width}`);
    assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
    await page.locator('#home-letter-form button').click();
    await page.waitForURL('**/submit-testimony');
    assert.equal(new URL(page.url()).search,'');
    assert.equal(await page.locator('[name=story]').inputValue(), words);
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('saint_charbel_letter_draft')),words);
    await page.reload();
    assert.equal(await page.locator('[name=story]').inputValue(), words);
    const revised = words + ' I wanted to add this detail on the second page.';
    await page.locator('[name=story]').fill(revised);
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('saint_charbel_letter_draft')),revised);
    await page.locator('[name=display_name]').fill('Test reader');
    for (const name of ['age_confirmed','consent_publish','ai_consent']) await page.locator(`[name=${name}]`).check();
    let succeed=false;
    await page.route('https://test.supabase.co/functions/v1/submit-testimony',route=>route.fulfill({status:succeed?202:503,contentType:'application/json',body:succeed?'{"accepted":true,"reference":"test-only"}':'{"message":"temporarily unavailable"}'}));
    await page.locator('#submit-testimony-btn').click();
    await page.waitForFunction(()=>document.getElementById('submit-status').textContent.includes('temporarily unavailable'));
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('saint_charbel_letter_draft')),revised);
    assert.equal(await page.locator('[name=story]').inputValue(),revised);
    await page.reload();
    assert.equal(await page.locator('[name=story]').inputValue(),revised);
    await page.goto(base+'/');
    assert.equal(await page.locator('#home-letter-draft').inputValue(),revised);
    await page.goto(base+'/submit-testimony');
    assert.equal(await page.locator('[name=story]').inputValue(),revised);
    await page.locator('[name=display_name]').fill('Test reader');
    for (const name of ['age_confirmed','consent_publish','ai_consent']) await page.locator(`[name=${name}]`).check();
    succeed=true;
    await page.locator('#submit-testimony-btn').click();
    await page.waitForFunction(()=>document.getElementById('submit-status').textContent.includes('test-only'));
    assert.equal(await page.evaluate(()=>sessionStorage.getItem('saint_charbel_letter_draft')),null);
    await context.close();
    console.log(`Home letter flow passed at ${width}`);
  }
  const context=await browser.newContext();
  await context.addInitScript(()=>{Object.defineProperty(window,'sessionStorage',{get(){throw new Error('blocked')}})});
  const page=await context.newPage();
  await page.goto(base+'/');
  await page.locator('#home-letter-draft').fill('A draft that cannot be transferred.');
  await page.locator('#home-letter-form button').click();
  assert.equal(new URL(page.url()).pathname,'/');
  assert.match(await page.locator('#home-letter-error').innerText(),/could not carry/);
  await context.close();
  console.log('Storage failure keeps the draft on the homepage.');
} finally { await browser.close(); }
