import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('output/playwright/testimonies',{recursive:true});
const base=process.env.BASE_URL||'http://127.0.0.1:4321';
const browser=await chromium.launch();
async function pageFor(mode,width=375){
 const page=await browser.newPage({viewport:{width,height:900},serviceWorkers:'block'});
 await page.route('**/testimony-config.js',r=>r.fulfill({contentType:'application/javascript',body:`window.TESTIMONY_CONFIG={supabaseUrl:'https://test.supabase.co',supabaseAnonKey:'public-key',turnstileSiteKey:'test',accountsEnabled:true,submissionsEnabled:true,moderationEnabled:true};`}));
 await page.route('**/cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:`
 window.calls=[];window.level='aal1';window.role=${JSON.stringify(mode.startsWith('admin')?'moderator':'member')};window.signedIn=${mode!=='admin-login'};
 const story={id:'one',author_id:'author',display_name:'A reader',story:'An experience of prayer and hope from my own life. '.repeat(3),status:'pending',review_state:'complete',revision:1,review_notes:{summary:'A report, not verified',recommendation:'review',flags:[],questions:[]}};
 window.row=story;window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:${mode==='guest'?'null':"{access_token:'token',user:{id:'author',email_confirmed_at:'2026-01-01'}}"}}}),getUser:async()=>({data:{user:window.signedIn?{id:'author',app_metadata:{role:window.role}}:null}}),onAuthStateChange:()=>{},signOut:async()=>{},signInWithOtp:async(args)=>{window.calls.push({name:'signInWithOtp',args});return {error:null}},signInWithPassword:async(args)=>{window.calls.push({name:'signInWithPassword',args});window.signedIn=true;return {error:null}},mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:window.level}}),listFactors:async()=>({data:{totp:[{id:'factor',status:'verified'}]}}),challengeAndVerify:async()=>{window.level='aal2';return {error:null}}}},
 from(table){window.calls.push({name:'from',table});let filter;const chain={select(){return chain},eq(k,v){filter=v;return chain},in(){return chain},order(){return chain},range(){return chain},limit(){return chain},single(){return chain},then(resolve){let data=[];if(table==='testimony_submissions')data=filter==='approved'?[]:[window.row];if(table==='testimony_controls')data={intake_enabled:true,publishing_enabled:true,screening_enabled:true};if(table==='testimony_publications')data=[{...window.row,label:'Reader-submitted testimony — reviewed for publication'}];return Promise.resolve({data,error:null}).then(resolve)}};return chain},
 rpc:async(name,args)=>{window.calls.push({name,args});if(name==='testimony_author_action')window.row={...window.row,status:args.p_action==='withdraw'?'withdrawn':'pending',story:args.p_payload?.story||window.row.story,display_name:args.p_payload?.display_name||window.row.display_name,revision:window.row.revision+1};return {data:{ok:true},error:null}}
 })};`}));
 await page.route('**/challenges.cloudflare.com/**',r=>r.fulfill({contentType:'application/javascript',body:`window.turnstile={render(host,opts){window.cap=opts;opts.callback('valid');return 'id'},reset(){window.cap.callback('valid')}};`}));
 return page;
}
try{
 for(const width of [375,1366]){
  const page=await pageFor('member',width);let sent;
  await page.route('https://test.supabase.co/functions/v1/submit-testimony',async r=>{sent=r.request().postDataJSON();await r.fulfill({status:202,contentType:'application/json',body:'{"accepted":true,"reference":"one"}'});});
  await page.goto(base+'/submit-testimony.html');await page.locator('[name=display_name]').fill('<img src=x onerror=alert(1)>');await page.locator('[name=story]').fill('My own experience of prayer and hope. '.repeat(4));
  for(const name of ['age_confirmed','consent_publish','ai_consent'])await page.locator(`[name=${name}]`).check();
  await page.locator('#submit-testimony-btn').click();assert.equal(await page.locator('#testimony-preview').isVisible(),true);assert.equal(await page.locator('#preview-content img').count(),0);assert.equal(sent,undefined);assert.equal(await page.locator('#testimony-form').isVisible(),false);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await page.screenshot({path:`output/playwright/testimonies/preview-${width}.png`,fullPage:true});
  await page.locator('#confirm-testimony').click();await page.waitForFunction(()=>document.getElementById('submit-status').textContent.includes('pending review'));assert.equal(sent.display_name,'<img src=x onerror=alert(1)>');assert.equal(sent.status,undefined);
  await page.goto(base+'/account.html');await page.locator('#my-testimonies article').waitFor();await page.locator('summary').click();await page.locator('#my-testimonies textarea').fill('Revised account of what I personally experienced. '.repeat(3));await page.getByRole('button',{name:'Save and send for review'}).click();await page.waitForFunction(()=>calls.some(c=>c.name==='testimony_author_action'));assert.equal((await page.evaluate(()=>calls.find(c=>c.name==='testimony_author_action'))).args.p_action,'edit');
  page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Withdraw and remove from website'}).click();await page.waitForFunction(()=>document.getElementById('my-testimonies').textContent.includes('withdrawn'));
  await page.close();console.log('Author preview, safe rendering, submit, edit and withdrawal passed at',width);
 }
 const login=await pageFor('admin-login');await login.goto(base+'/testimony-review.html');await login.locator('[name=email]').fill('owner@example.test');await login.locator('[name=password]').fill('test-password');await login.getByRole('button',{name:'Login',exact:true}).click();await login.locator('#admin-mfa-form').waitFor();assert.equal((await login.evaluate(()=>calls.find(c=>c.name==='signInWithPassword'))).args.options.captchaToken,'valid');await login.close();
 const admin=await pageFor('admin');await admin.goto(base+'/testimony-review.html');await admin.locator('#admin-mfa-form').waitFor();assert.equal(await admin.locator('#admin-panel').isVisible(),false);assert.equal(await admin.evaluate(()=>calls.some(c=>c.name==='from')),false);
 await admin.locator('[name=code]').fill('123456');await admin.getByRole('button',{name:'Verify authenticator'}).click();await admin.locator('#pending-list article').waitFor();assert.equal(await admin.locator('#admin-login-form').isVisible(),false);assert.equal(await admin.locator('#admin-mfa-form').isVisible(),false);assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await admin.screenshot({path:'output/playwright/testimonies/moderator-mobile.png',fullPage:true});await admin.getByRole('button',{name:'Approve and publish'}).click();await admin.waitForFunction(()=>calls.some(c=>c.name==='testimony_moderate'));assert.equal((await admin.evaluate(()=>calls.find(c=>c.name==='testimony_moderate'))).args.p_revision,1);
 await admin.getByRole('button',{name:'Pause intake, AI, and publishing'}).click();await admin.waitForFunction(()=>calls.some(c=>c.name==='testimony_set_controls'));assert.deepEqual((await admin.evaluate(()=>calls.find(c=>c.name==='testimony_set_controls'))).args,{p_intake:false,p_publishing:false,p_screening:false});await admin.close();
 const ordinary=await pageFor('member');await ordinary.goto(base+'/testimony-review.html');await ordinary.waitForFunction(()=>document.getElementById('admin-status').textContent.includes('moderator only'));assert.equal(await ordinary.locator('#admin-panel').isVisible(),false);assert.equal(await ordinary.evaluate(()=>calls.some(c=>c.name==='from')),false);await ordinary.close();
 const pub=await pageFor('member');await pub.goto(base+'/testimonies.html');await pub.getByText('Report this testimony').first().waitFor();assert.equal(await pub.evaluate(()=>calls.some(c=>c.table==='testimony_submissions')),false);await pub.getByText('Report this testimony').first().click();await pub.locator('textarea').first().fill('Please review the details of this account.');await pub.getByRole('button',{name:'Send report'}).first().click();await pub.waitForFunction(()=>calls.some(c=>c.name==='testimony_report'));await pub.close();
 const guest=await pageFor('guest');await guest.goto(base+'/account.html');await guest.locator('[name=email]').fill('reader@example.test');await guest.getByRole('button',{name:'Continue securely'}).click();await guest.waitForFunction(()=>calls.some(c=>c.name==='signInWithOtp'));assert.equal((await guest.evaluate(()=>calls.find(c=>c.name==='signInWithOtp'))).args.options.captchaToken,'valid');await guest.close();
 console.log('MFA gate, owner decisions, emergency pause, public projection, reports, and email sign-in browser checks passed.');
}finally{await browser.close();}
