import assert from 'node:assert/strict';
import { chromium } from 'playwright';
import { mkdir } from 'node:fs/promises';
await mkdir('output/playwright/testimonies',{recursive:true});
const base=process.env.BASE_URL||'http://127.0.0.1:4321';
const browser=await chromium.launch();
async function pageFor(mode,width=375){
 const page=await browser.newPage({viewport:{width,height:900},serviceWorkers:'block'});
 await page.route('**/testimony-config.js*',r=>r.fulfill({contentType:'application/javascript',body:`window.TESTIMONY_CONFIG={supabaseUrl:'https://test.supabase.co',supabaseAnonKey:'public-key',turnstileSiteKey:'test',accountsEnabled:true,submissionsEnabled:true,moderationEnabled:true,moderatorMfaRequired:${!mode.startsWith('admin-password')} };`}));
 await page.route('**/cdn.jsdelivr.net/**',r=>r.fulfill({contentType:'application/javascript',body:`
 window.calls=[];window.level='aal1';window.role=${JSON.stringify(mode.startsWith('admin')?'moderator':'member')};window.signedIn=${!mode.endsWith('-login')};if(sessionStorage.getItem('mock-signed-out'))window.signedIn=false;
 const story={id:'one',author_id:'author',display_name:'A reader',story:'An experience of prayer and hope from my own life. '.repeat(3),status:'pending',review_state:'complete',revision:1,review_notes:{summary:'A report, not verified',recommendation:'review',flags:[],questions:[]}};
 window.row=story;window.supabase={createClient:()=>({auth:{getSession:async()=>({data:{session:${mode==='guest'?'null':"{access_token:'token',user:{id:'author',email_confirmed_at:'2026-01-01'}}"}}}),getUser:async()=>({data:{user:window.signedIn?{id:'author',app_metadata:{role:window.role}}:null}}),onAuthStateChange:()=>{},signOut:async()=>{window.signedIn=false;sessionStorage.setItem('mock-signed-out','yes');return {error:null}},signInWithOtp:async(args)=>{window.calls.push({name:'signInWithOtp',args});return {error:null}},signInWithPassword:async(args)=>{window.calls.push({name:'signInWithPassword',args});if(window.failLogin)return {error:{message:'invalid'}};window.signedIn=true;sessionStorage.removeItem('mock-signed-out');return {error:null}},mfa:{getAuthenticatorAssuranceLevel:async()=>({data:{currentLevel:window.level}}),listFactors:async()=>({data:{all:[{id:'abandoned',factor_type:'totp',status:'unverified'}],totp:${mode==='admin-enroll'?'[]':"[{id:'factor',status:'verified'}]"}}}),unenroll:async(args)=>{window.calls.push({name:'unenroll',args});return {error:null}},enroll:async()=>({data:{id:'new-factor',totp:{secret:'TEST-ONLY',qr_code:'data:image/svg+xml;charset=utf-8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20width%3D%22200%22%20height%3D%22200%22%3E%3Crect%20width%3D%22200%22%20height%3D%22200%22%2F%3E%3C%2Fsvg%3E'}}}),challengeAndVerify:async()=>{window.level='aal2';return {error:null}}}},
 from(table){window.calls.push({name:'from',table});let filter;const chain={select(){return chain},eq(k,v){filter=v;return chain},in(){return chain},order(){return chain},range(){return chain},limit(){return chain},single(){return chain},then(resolve){let data=[];if(table==='testimony_submissions')data=filter==='approved'?[]:[window.row];if(table==='testimony_controls')data={intake_enabled:true,publishing_enabled:true,screening_enabled:true};if(table==='testimony_publications')data=[{...window.row,label:'Reader-submitted testimony — reviewed for publication'}];return Promise.resolve({data,error:window.loadError?{message:'offline'}:null}).then(resolve)}};return chain},
 rpc:async(name,args)=>{window.calls.push({name,args});if(window.rpcError)return {error:{message:window.rpcError}};if(name==='testimony_manual_review')window.row={...window.row,review_state:'complete',revision:window.row.revision+1,review_notes:{source:'human',summary:args.p_reason}};if(name==='testimony_author_action')window.row={...window.row,status:args.p_action==='withdraw'?'withdrawn':'pending',story:args.p_payload?.story||window.row.story,display_name:args.p_payload?.display_name||window.row.display_name,revision:window.row.revision+1};return {data:{ok:true},error:null}}
 })};`}));
 await page.route('**/challenges.cloudflare.com/**',r=>r.fulfill({contentType:'application/javascript',body:`window.turnstile={render(host,opts){window.cap=opts;opts.callback('valid');return 'id'},reset(){window.cap.callback('valid')}};`}));
 return page;
}
try{
 for(const width of [375,1366]){
  const page=await pageFor('member',width);let sent;
  await page.route('https://test.supabase.co/functions/v1/submit-testimony',async r=>{sent=r.request().postDataJSON();await r.fulfill({status:202,contentType:'application/json',body:'{"accepted":true,"reference":"one"}'});});
  await page.goto(base+'/submit-testimony.html');await page.locator('[name=display_name]').fill('<img src=x onerror=alert(1)>');await page.locator('[name=story]').fill('My own experience of prayer and hope. '.repeat(4));
  for(const name of ['age_confirmed','consent_publish','ai_consent'])await page.locator(`[name=${name}]`).check();
  assert.equal(await page.getByRole('button',{name:'Submit testimony',exact:true}).count(),1);
  assert.equal(await page.locator('#testimony-preview').count(),0);
  await page.evaluate(()=>cap['expired-callback']());
  assert.equal(await page.getByRole('button',{name:'Submit testimony',exact:true}).isDisabled(),true);await page.locator('#testimony-form').evaluate(form=>form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true})));assert.equal(sent,undefined);
  assert.ok((await page.locator('#submit-status').innerText()).includes('human verification'));
  await page.evaluate(()=>cap.callback('valid'));
  assert.equal(await page.locator('#submit-testimony-btn').isEnabled(),true);
  await page.locator('[name=consent_publish]').uncheck();assert.equal(await page.locator('#submit-testimony-btn').isDisabled(),true);
  await page.locator('[name=consent_publish]').check();
  await page.evaluate(()=>cap['error-callback']());assert.equal(await page.locator('#submit-testimony-btn').isDisabled(),true);
  await page.evaluate(()=>cap.callback('valid'));
  await page.getByRole('button',{name:'Submit testimony',exact:true}).click();
  await page.waitForFunction(()=>document.getElementById('submit-status').textContent.includes('pending review'));
  assert.equal(sent.display_name,'<img src=x onerror=alert(1)>');assert.equal(sent.status,undefined);
  assert.equal(await page.locator('[name=story]').inputValue(),'');assert.equal(await page.locator('#submit-testimony-btn').isDisabled(),true);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
  await page.screenshot({path:`output/playwright/testimonies/submitted-${width}.png`,fullPage:true});
  await page.goto(base+'/account.html');await page.locator('#my-testimonies article').waitFor();await page.locator('summary').click();await page.locator('#my-testimonies textarea').fill('Revised account of what I personally experienced. '.repeat(3));await page.getByRole('button',{name:'Save and send for review'}).click();await page.waitForFunction(()=>calls.some(c=>c.name==='testimony_author_action'));assert.equal((await page.evaluate(()=>calls.find(c=>c.name==='testimony_author_action'))).args.p_action,'edit');
  page.on('dialog',d=>d.accept());await page.getByRole('button',{name:'Withdraw and remove from website'}).click();await page.waitForFunction(()=>document.getElementById('my-testimonies').textContent.includes('withdrawn'));
  await page.close();console.log('Direct submission with CAPTCHA, edit and withdrawal passed at',width);
 }
 const retrySubmission=await pageFor('member');let submissionCalls=0;
 await retrySubmission.route('https://test.supabase.co/functions/v1/submit-testimony',async route=>{submissionCalls++;await new Promise(r=>setTimeout(r,200));await route.fulfill({status:503,contentType:'application/json',body:'{"message":"Submissions are temporarily paused."}'});});
 await retrySubmission.goto(base+'/submit-testimony.html');await retrySubmission.locator('[name=display_name]').fill('Demo reader');await retrySubmission.locator('[name=story]').fill('A test story that should remain in the form when the service is unavailable.');
 for(const name of ['age_confirmed','consent_publish','ai_consent'])await retrySubmission.locator(`[name=${name}]`).check();
 await retrySubmission.locator('#testimony-form').evaluate(form=>{form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));form.dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}));});
 await retrySubmission.waitForFunction(()=>document.getElementById('submit-status').textContent.includes('temporarily paused'));
 assert.equal(submissionCalls,1);assert.ok((await retrySubmission.locator('[name=story]').inputValue()).includes('remain in the form'));assert.equal(await retrySubmission.getByRole('button',{name:'Submit testimony',exact:true}).isEnabled(),true);await retrySubmission.close();
 const pausedCaptcha=await pageFor('guest');await pausedCaptcha.route('**/testimony-config.js*',r=>r.fulfill({contentType:'application/javascript',body:"window.TESTIMONY_CONFIG={supabaseUrl:'https://test.supabase.co',supabaseAnonKey:'public-key',turnstileSiteKey:'test',submissionsEnabled:false};"}));await pausedCaptcha.goto(base+'/submit-testimony.html');await pausedCaptcha.getByText('Human verification complete.',{exact:true}).waitFor();assert.equal(await pausedCaptcha.getByRole('button',{name:'Submit testimony',exact:true}).isDisabled(),true);await pausedCaptcha.close();
 const hcap=await pageFor('submit');
 await hcap.route('**/testimony-config.js*',r=>r.fulfill({contentType:'application/javascript',body:"window.TESTIMONY_CONFIG={supabaseUrl:'https://test.supabase.co',supabaseAnonKey:'public-key',submissionCaptchaProvider:'hcaptcha',hcaptchaSiteKey:'test-site',submissionsEnabled:false};"}));
 await hcap.route('**/js.hcaptcha.com/**',r=>r.fulfill({contentType:'application/javascript',body:"window.hcaptcha={render(host,opts){window.cap=opts;window.hcapRenders=(window.hcapRenders||0)+1;host.textContent='TEST ONLY hCaptcha widget';return 'id'},remove(){},reset(){}};window.testimonyCaptchaLoaded_hcaptcha();"}));
 await hcap.goto(base+'/submit-testimony.html');
 await hcap.getByText('Check “I am human” above to continue.',{exact:true}).waitFor();
 await hcap.locator('[name=story]').fill('My story remains here while I retry a failed human verification check.');
 await hcap.evaluate(()=>window.cap['error-callback']('network-error'));
 await hcap.getByRole('button',{name:'Retry human verification',exact:true}).click();
 assert.equal(await hcap.evaluate(()=>window.hcapRenders),2);
 assert.ok((await hcap.locator('[name=story]').inputValue()).startsWith('My story remains here'));
 await hcap.evaluate(()=>window.cap.callback('valid-test-token'));
 await hcap.getByText('Human verification complete.',{exact:true}).waitFor();
 await hcap.evaluate(()=>window.cap['expired-callback']());
 assert.equal(await hcap.getByRole('button',{name:'Submit testimony',exact:true}).isDisabled(),true);
 await hcap.close();
 console.log('hCaptcha widget lifecycle passed: visible instruction, failure, retry, preserved story, success and expiry. Provider responses are mocked.');
 const guestIntake=await pageFor('guest');let guestPost;
 await guestIntake.route('https://test.supabase.co/functions/v1/submit-testimony',r=>{guestPost=r.request();return r.fulfill({status:202,contentType:'application/json',body:'{"accepted":true,"reference":"guest-reference"}'});});
 await guestIntake.goto(base+'/submit-testimony.html');
 await guestIntake.locator('[name=display_name]').fill('Guest example');await guestIntake.locator('[name=story]').fill('This is a synthetic guest example used only to test the private moderation flow.');
 for(const name of ['age_confirmed','consent_publish','ai_consent'])await guestIntake.locator(`[name=${name}]`).check();
 await guestIntake.getByRole('button',{name:'Submit testimony',exact:true}).click();
 await guestIntake.getByText(/Save this reference: guest-reference/).waitFor();assert.equal(guestPost.headers().authorization,undefined);await guestIntake.close();
 const humanReview=await pageFor('admin-password');await humanReview.goto(base+'/testimony-review.html');await humanReview.locator('#pending-list article').first().waitFor();
 await humanReview.evaluate(()=>{window.row.review_state='queued';window.row.review_notes=null;});await humanReview.getByRole('button',{name:'Refresh reviews',exact:true}).click();
 await humanReview.getByRole('button',{name:'Record my manual review',exact:true}).click();await humanReview.getByText('Enter review notes of at least 30 characters.',{exact:true}).waitFor();
 await humanReview.locator('#pending-list textarea').fill('I read the entire synthetic story and checked it for spam and private information.');await humanReview.getByRole('button',{name:'Record my manual review',exact:true}).click();
 await humanReview.getByText('Moderator review notes',{exact:true}).waitFor();assert.equal(await humanReview.getByRole('button',{name:'Approve and publish',exact:true}).isEnabled(),true);await humanReview.close();
 console.log('Guest submission without login and explicit manual-review-to-approval UI checks passed. Backend responses are mocked.');
 const login=await pageFor('admin-login');await login.goto(base+'/testimony-review.html');await login.locator('[name=email]').fill('owner@example.test');await login.locator('[name=password]').fill('test-password');await login.getByRole('button',{name:'Login',exact:true}).click();await login.locator('#admin-mfa-form').waitFor();assert.equal((await login.evaluate(()=>calls.find(c=>c.name==='signInWithPassword'))).args.options.captchaToken,'valid');await login.close();
 const enrollment=await pageFor('admin-enroll');await enrollment.goto(base+'/testimony-review.html');await enrollment.locator('#admin-mfa-form').waitFor();await enrollment.waitForFunction(()=>{const img=document.getElementById('mfa-qr');return img.complete&&img.naturalWidth>0;});assert.equal(await enrollment.locator('#admin-panel').isVisible(),false);assert.equal((await enrollment.evaluate(()=>calls.find(c=>c.name==='unenroll'))).args.factorId,'abandoned');await enrollment.close();
 const passwordAdmin=await pageFor('admin-password');await passwordAdmin.goto(base+'/testimony-review.html');await passwordAdmin.locator('#pending-list article').waitFor();assert.equal(await passwordAdmin.locator('#admin-mfa-form').isVisible(),false);assert.equal(await passwordAdmin.locator('#admin-panel').isVisible(),true);await passwordAdmin.close();
 for(const demoWidth of [375,768,1366]){const demo=await pageFor('admin-password',demoWidth);await demo.goto(base+'/testimony-review.html?demo=1');await demo.locator('#demo-notice').waitFor();assert.equal(await demo.locator('#pending-list article').count(),3);await demo.getByRole('button',{name:'Approve demo',exact:true}).first().click();assert.equal(await demo.locator('#approved-list article').count(),1);const rejectCard=demo.locator('#pending-list article').last();await rejectCard.getByRole('button',{name:'Reject',exact:true}).click();assert.equal(await rejectCard.getByRole('alert').isVisible(),true);assert.equal(await rejectCard.locator('textarea').getAttribute('aria-invalid'),'true');assert.equal(await rejectCard.locator('textarea').evaluate(el=>el===document.activeElement),true);await rejectCard.locator('textarea').fill('short');await rejectCard.getByRole('button',{name:'Reject',exact:true}).click();assert.equal(await demo.locator('#pending-list article').count(),2);await rejectCard.locator('textarea').fill('Demo rejection of promotional material.');await rejectCard.getByRole('button',{name:'Reject',exact:true}).click();assert.equal(await demo.locator('#pending-list article').count(),1);assert.equal(await demo.evaluate(()=>calls.some(c=>c.name==='from'||c.name==='testimony_moderate')),false);assert.equal(await demo.locator('#demo-rejected article').count(),1);
 const clarification=demo.locator('#pending-list article');await clarification.locator('textarea').fill('Please explain when this happened.');await clarification.getByRole('button',{name:'Request clarification',exact:true}).click();assert.equal(await demo.getByRole('button',{name:'Approve demo',exact:true}).isDisabled(),true);await demo.getByRole('button',{name:'Simulate author reply',exact:true}).click();assert.equal(await demo.getByRole('button',{name:'Approve demo',exact:true}).isEnabled(),true);
 const published=demo.locator('#approved-list article');await published.getByRole('button',{name:'Unpublish',exact:true}).click();assert.equal(await published.getByRole('alert').isVisible(),true);await published.locator('textarea').fill('Return this demo for another review.');await published.getByRole('button',{name:'Unpublish',exact:true}).click();assert.equal(await demo.locator('#approved-list article').count(),0);
 await demo.getByRole('button',{name:'Reset demo stories',exact:true}).click();assert.equal(await demo.locator('#pending-list article').count(),3);assert.equal(await demo.locator('#demo-rejected article').count(),0);assert.equal(await demo.evaluate(()=>calls.some(c=>c.name==='from'||c.name==='testimony_moderate')),false);assert.equal(await demo.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);
 await demo.screenshot({path:`output/playwright/testimonies/demo-${demoWidth}.png`,fullPage:true});await demo.close();console.log('Complete demo approve/reject/clarify/reply/unpublish/reset cycle passed at',demoWidth);}
 const failures=await pageFor('admin-password-login');await failures.goto(base+'/testimony-review.html');await failures.locator('[name=email]').fill('owner@example.test');await failures.locator('[name=password]').fill('test-password');await failures.evaluate(()=>{cap['expired-callback']();});await failures.getByRole('button',{name:'Login',exact:true}).click();await failures.waitForFunction(()=>document.getElementById('admin-status').textContent.includes('human verification'));assert.equal(await failures.evaluate(()=>calls.some(c=>c.name==='signInWithPassword')),false);
 await failures.evaluate(()=>{window.failLogin=true;cap.callback('valid');});await failures.getByRole('button',{name:'Login',exact:true}).click();await failures.waitForFunction(()=>document.getElementById('admin-status').textContent.includes('Sign-in failed'));assert.equal(await failures.locator('#admin-panel').isVisible(),false);
 await failures.evaluate(()=>{window.failLogin=false;});await failures.getByRole('button',{name:'Login',exact:true}).click();await failures.locator('#pending-list article').waitFor();await failures.evaluate(()=>{window.rpcError='publishing_paused';});await failures.getByRole('button',{name:'Approve and publish',exact:true}).click();await failures.waitForFunction(()=>document.getElementById('admin-feedback').textContent.includes('Publishing is paused'));assert.equal(await failures.locator('#admin-feedback').evaluate(el=>el===document.activeElement),true);assert.equal(await failures.getByRole('button',{name:'Approve and publish',exact:true}).isEnabled(),true);
 await failures.getByRole('button',{name:'Forget this browser and sign out',exact:true}).click();await failures.locator('#admin-login-form').waitFor();assert.equal(await failures.locator('#admin-panel').isVisible(),false);await failures.close();console.log('Expired CAPTCHA, bad password, server rejection, retry and sign-out checks passed.');
 const offline=await pageFor('admin-password');await offline.addInitScript(()=>{window.loadError=true;});await offline.goto(base+'/testimony-review.html');await offline.getByRole('button',{name:'Retry loading admin panel'}).waitFor();assert.equal(await offline.locator('#admin-panel').isVisible(),false);await offline.evaluate(()=>{window.loadError=false;});await offline.getByRole('button',{name:'Retry loading admin panel'}).click();await offline.locator('#pending-list article').waitFor();await offline.close();console.log('Failed queue load stays closed and retry recovers.');
 const admin=await pageFor('admin');await admin.goto(base+'/testimony-review.html');await admin.locator('#admin-mfa-form').waitFor();assert.equal(await admin.locator('#admin-panel').isVisible(),false);assert.equal(await admin.evaluate(()=>calls.some(c=>c.name==='from')),false);
 await admin.locator('[name=code]').fill('123456');await admin.getByRole('button',{name:'Verify authenticator'}).click();await admin.locator('#pending-list article').waitFor();assert.equal(await admin.locator('#admin-login-form').isVisible(),false);assert.equal(await admin.locator('#admin-mfa-form').isVisible(),false);assert.equal(await admin.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1),true);await admin.screenshot({path:'output/playwright/testimonies/moderator-mobile.png',fullPage:true});await admin.getByRole('button',{name:'Approve and publish'}).click();await admin.waitForFunction(()=>calls.some(c=>c.name==='testimony_moderate'));assert.equal((await admin.evaluate(()=>calls.find(c=>c.name==='testimony_moderate'))).args.p_revision,1);
 await admin.getByRole('button',{name:'Pause intake, AI, and publishing'}).click();await admin.waitForFunction(()=>calls.some(c=>c.name==='testimony_set_controls'));assert.deepEqual((await admin.evaluate(()=>calls.find(c=>c.name==='testimony_set_controls'))).args,{p_intake:false,p_publishing:false,p_screening:false});await admin.close();
 const ordinary=await pageFor('member');await ordinary.goto(base+'/testimony-review.html');await ordinary.waitForFunction(()=>document.getElementById('admin-status').textContent.includes('moderator only'));assert.equal(await ordinary.locator('#admin-panel').isVisible(),false);assert.equal(await ordinary.evaluate(()=>calls.some(c=>c.name==='from')),false);await ordinary.close();
 const pub=await pageFor('member');await pub.goto(base+'/testimonies.html');await pub.getByText('Report this testimony').first().waitFor();assert.equal(await pub.evaluate(()=>calls.some(c=>c.table==='testimony_submissions')),false);await pub.getByText('Report this testimony').first().click();await pub.locator('textarea').first().fill('Please review the details of this account.');await pub.getByRole('button',{name:'Send report'}).first().click();await pub.waitForFunction(()=>calls.some(c=>c.name==='testimony_report'));await pub.close();
 const guest=await pageFor('guest');await guest.goto(base+'/account.html');await guest.locator('[name=email]').fill('reader@example.test');await guest.getByRole('button',{name:'Continue securely'}).click();await guest.waitForFunction(()=>calls.some(c=>c.name==='signInWithOtp'));assert.equal((await guest.evaluate(()=>calls.find(c=>c.name==='signInWithOtp'))).args.options.captchaToken,'valid');await guest.close();
 console.log('MFA gate, owner decisions, emergency pause, public projection, reports, and email sign-in browser checks passed.');
}finally{await browser.close();}
