#!/usr/bin/env python3
"""Build one Arabic feature from the existing EN news feature, never the archive."""
import argparse
import html
import json
import re
import subprocess
from pathlib import Path
from string import Template
from bs4 import BeautifulSoup
ROOT = Path(__file__).resolve().parents[1]
FEATURE_ID = 'charbel-premiere-release-2026-10'
ROUTE = '/ar/charbel-film-premiere'
CHARITY_SOURCE = 'https://www.lorientlejour.com/article/1550058/la-projection-du-film-charbel-au-profit-de-anta-akhi.html'

def feature_template(root):
    source = (root / 'templates/news-desk/cards.html').read_text()
    soup = BeautifulSoup(source, 'html.parser')
    blocks = soup.select('article#' + FEATURE_ID)
    if len(blocks) != 1:
        raise ValueError('Expected exactly one premiere feature')
    block = blocks[0]
    keys = set(re.findall(r'\$\{([^}]+)\}', str(block)))
    if not keys or any(not k.startswith('premiere.') for k in keys):
        raise ValueError('Feature contains out-of-scope catalog keys')
    # A standalone article needs one H1, not the archive card's linked H3.
    heading = block.find('h3', recursive=False)
    if heading is None or heading.get_text() != '${premiere.title}':
        raise ValueError('Unexpected premiere heading')
    heading.name = 'h1'
    heading.a.unwrap()
    block['class'] = ['film-news-article']
    block.select_one('h4').name = 'h2'
    return str(block), keys

def render_source(root=ROOT):
    registry = json.loads((root / 'locales/registry.json').read_text())
    arabic = json.loads((root / 'locales/ar/film-premiere-copy.json').read_text())
    _, expected = feature_template(root)
    if set(arabic) != expected:
        raise ValueError('Arabic premiere keys must exactly match EN feature catalog')
    if any(not isinstance(v, str) or not v.strip() or re.search(r'<\s*/?\s*[A-Za-z!]', v) for v in arabic.values()):
        raise ValueError('Arabic copy must be nonempty plain text')
    source, keys = feature_template(root)
    content = re.sub(r'\$\{([^}]+)\}', lambda m: html.escape(arabic[m[1]], quote=True), source)
    common = json.loads((root / 'locales/ar/common.json').read_text())
    site = registry['site']; url = site + ROUTE
    # Shared serializer owns WebPage structure; no hand-added schema block.
    args = [arabic['premiere.title'], arabic['premiere.body'], url,
            common['navigation.home'], site+'/ar/', arabic['premiere.title'], url]
    args = [json.dumps(v,ensure_ascii=False)[1:-1].replace('<','\\u003c').replace('&','\\u0026') for v in args]
    script = "import {renderWebPage} from './scripts/lib/jsonld.mjs';process.stdout.write(renderWebPage(JSON.parse(process.argv[1])))"
    schema_block = subprocess.check_output(['node','--input-type=module','-e',script,json.dumps(args,ensure_ascii=False)],cwd=root,text=True)
    schema = re.search(r'<script[^>]*>([\s\S]*)</script>',schema_block)[1].strip()
    template = Template((root / 'templates/international/page.html').read_text())
    # Reuse the existing international article shell, with the shared film-video CSS.
    text = template.substitute(language='ar', direction='rtl', title=html.escape(arabic['premiere.title']), description=html.escape(arabic['premiere.release']), canonical=url,
        alternates='<link rel="alternate" hreflang="ar" href="'+url+'" />',
        oglocale='<meta property="og:locale" content="ar_AR" />', brand=html.escape(common['site.brand']), site=site,
        schema=schema, skip=html.escape(common['navigation.skip']), home='/ar/',
        chooseLanguage=html.escape(common['navigation.chooseLanguage']), navigation='<a href="/news#'+FEATURE_ID+'" lang="en" dir="ltr">'+html.escape(registry['locales']['en']['nativeName'])+'</a>',
        homeLabel=html.escape(common['navigation.home']), content=content, footer=html.escape(common['site.footer']))
    text = text.replace('<!-- Generated by npm run i18n:build. Edit locales/, not this HTML. -->','<!-- Generated by npm run i18n:build (scripts/build_film_news_ar.py). Edit locales/ar/film-premiere*.json and EN feature template. -->')
    text = text.replace('<link rel="stylesheet" href="/international.css', '<link rel="stylesheet" href="/styles.css?v=20261002-share-2" />\n<link rel="stylesheet" href="/international.css')
    text = text.replace('</head>', '<style>.film-news-article p a{text-decoration:underline;text-underline-offset:.15em}</style>\n</head>')
    labels = json.loads((root / 'locales/ar/share.json').read_text())
    text = text.replace('</head>', '<script type="application/json" id="sc-share-labels">'+json.dumps(labels,ensure_ascii=False).replace('<','\\u003c')+'</script>\n</head>')
    text = text.replace('</body>', '<script defer src="/share.js?v=20261002-share-2" data-share-mode="page"></script>\n</body>')
    return root / (ROUTE.lstrip('/')+'.html'), text

def output(root=ROOT):
    # The exact final manifest depends on ALL generated candidate pages and their
    # evidence overlays. A singleton control pass could silently change availability.
    # Use the whole international pipeline, which calls render_source above and
    # the shared postprocess_outputs function once. No circular output() call.
    import importlib.util
    spec = importlib.util.spec_from_file_location('film_international_pipeline', root / 'scripts/build-international.py')
    pipeline = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(pipeline)
    path = root / (ROUTE.lstrip('/') + '.html')
    return path, pipeline.outputs(root)[path]

def main():
    parser = argparse.ArgumentParser(); parser.add_argument('--check', action='store_true'); args = parser.parse_args()
    path, text = output()
    if args.check:
        if not path.exists() or path.read_text() != text: raise SystemExit('Arabic film feature stale')
    else:
        path.parent.mkdir(parents=True,exist_ok=True); path.write_text(text)
if __name__ == '__main__': main()
